using Photon.Pun;
using UnityEngine;

public class OnlineFruit : MonoBehaviour
{
    public GameObject whole;
    public GameObject sliced;

    private Rigidbody fruitRigidbody;
    private Collider fruitCollider;
    private ParticleSystem juiceEffect;

    public int points = 1;/*điểm nhận khi chém trùng vật thể*/

    private void Awake()/*Gán rigidbody và collider*/
    {
        fruitRigidbody = GetComponent<Rigidbody>();
        fruitCollider = GetComponent<Collider>();
        juiceEffect = GetComponentInChildren<ParticleSystem>();
    }

    private void Slice(Vector3 direction, Vector3 position, float force, bool isMine)
    {
        if (isMine)
        {
            OnlineGameManager.Instance.IncreaseScore(points);
        }
        

        // Tăt whole fruit
        fruitCollider.enabled = false;
        whole.SetActive(false);

        // Bật the sliced fruit
        sliced.SetActive(true);
        juiceEffect.Play();

        // Xoay dựa trên góc slice
        float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg;
        sliced.transform.rotation = Quaternion.Euler(0f, 0f, angle);

        Rigidbody[] slices = sliced.GetComponentsInChildren<Rigidbody>();

        // Thêm một lực cho mỗi slice dựa trên hướng lưỡi đao
        foreach (Rigidbody slice in slices)
        {
            slice.velocity = fruitRigidbody.velocity;
            slice.AddForceAtPosition(direction * force, position, ForceMode.Impulse);
        }
    }

    private void OnTriggerEnter(Collider other)/*kiểm tra va chạm của blade với vật thể*/
    {
        if (other.CompareTag("Player"))
        {
            var photonView = other.GetComponent<PhotonView>();
            if (photonView != null)
            {
                BladeOnline bladeOnline = other.GetComponent<BladeOnline>();
                Slice(bladeOnline.Direction, bladeOnline.transform.position, bladeOnline.sliceForce, photonView.IsMine);
            }
            

        }     
    }

}
